const menuItems = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 15.99,
    img: "https://media.istockphoto.com/id/454141675/photo/pancakes-with-berries-and-maple-syrup.jpg?s=612x612&w=0&k=20&c=sQVQl-4-WG2fkwOCJdVOz_qaO4B5Ebc7uxxWY3ajmrE=",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },

  {
    id: 2,
    title: "diner double",
    category: "lunch",
    price: 13.99,
    img: "https://media-cdn.tripadvisor.com/media/photo-s/1a/86/9d/db/canada-s-diner-double.jpg",
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "shakes",
    price: 6.99,
    img: "https://100-react-projects-day-85-dynamic-restaurant-menu.netlify.app/images/item-3.jpeg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: "country delight",
    category: "breakfast",
    price: 20.99,
    img: "https://entrackr.com/storage/2020/11/country-delight-1.jpg",
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: "egg attack",
    category: "lunch",
    price: 22.99,
    img: "https://static.vecteezy.com/system/resources/previews/019/023/604/non_2x/front-view-tasty-meat-burger-with-cheese-and-salad-free-photo.jpg",
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 18.99,
    img: "https://thumbs.dreamstime.com/z/enjoy-ultimate-oreo-milkshake-ai-generated-image-featuring-tall-glass-filled-creamy-blend-vanilla-ice-cream-276170279.jpg",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "breakfast",
    price: 8.99,
    img: "https://www.shutterstock.com/image-photo/hot-fried-bacon-pieces-cast-600nw-1046058229.jpg",
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: "american classic",
    category: "lunch",
    price: 12.99,
    img: "https://thumbs.dreamstime.com/b/assorted-american-food-top-view-109748438.jpg",
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "shakes",
    price: 16.99,
    img: "https://media.istockphoto.com/id/454141675/photo/pancakes-with-berries-and-maple-syrup.jpg?s=612x612&w=0&k=20&c=sQVQl-4-WG2fkwOCJdVOz_qaO4B5Ebc7uxxWY3ajmrE=",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menuItems;
